# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ec914d5b4f0ce1544b801aade61523ac2f7a5589f15fcd9f12f3ebc7ce6d5c862208d8c0f7f8bfa0e267c10b59561ec3aa9bff420606f7b48e5d125d3503b65

test:
  secret_key_base: 403417c6688a454a901a51f19fb84d01de1256bca5f14eb7f46f55890ff2db61fd910dc7664d6b19978540ff84efcbc5d770a5335438405a12fd6946f74ea86f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
